### ISSUE TITLE
"Cache-Tags" header being appended for non tags routes

### ISSUE THREAD

**Issue by Dibbyo456** [yediyuz/laravel-cloudflare-cache#15]
```php
Route::cache()->group(function () {
    Route::get('/content', function () {
        return 'content';
    });
});

Route::cache(tags: ['tag1', 'tag2'])->group(function () {
    Route::get('/content_with_tags', function () {
        return 'content';
    });
});
```

```console
curl -sIXGET http://127.0.0.1:8000/content

HTTP/1.1 200 OK
Host: 127.0.0.1:8000
Connection: close
X-Powered-By: PHP/8.3.4
Content-Type: text/html; charset=UTF-8
Cache-Control: max-age=600, public
Date: Sat, 30 Mar 2024 22:31:46 GMT
Cache-Tags: tag1,tag2
```

The `Cache-Tags` being appended for `/content` route, which is a bug.

<img width="1582" alt="Screenshot 2024-03-31 at 4 10 19 AM" src="https://github.com/yediyuz/laravel-cloudflare-cache/assets/18257605/f7ba4fb3-e020-4916-ade3-544203a7cc59">

**Comment by Dibbyo456** [comment]
@mertasan Mentioned commit does not solve the issue.

The `Cache-Tags: tag1,tag2` header is appending for `/content` route, where it should only be appending for `/content_with_tags` route.

In order to reproduce make sure you are using given template.

**Comment by mertasan** [comment]
Hey Harry,

Thank you for the issues and feedback! #18
